version: "3.7"

services:
  sample:
    image: landingpage:1.0
    container_name: landingpage_test
    build:
      context: "./"
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
